loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path, re_path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name="pagar"),
    path('salvarpedido/', views.SalvarPedido.as_view(), name="salvarpedido"),
    path('lista/', views.Lista.as_view(), name="lista"),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name="detalhe"),
    re_path(r'^export-exl/$', views.export, name='export'),
    re_path('grafico/', views.main_view, name='grafico'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'
        db_table = "pedido_itempedido"

    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promo = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

pedido/views.py
from typing import Any
from django import http
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from pedido.resources import ItemPedidoResource

from .utils import get_plot
from produto.models import Variacao
from .models import Pedido, ItemPedido

from utils import utils


class DispatchLoginRequiredMixin(View):
    # Permite apenas usuários logados
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    # Permite que o usuário veja apenas os seus pedidos
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        # Verificar se o usuário está logado
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login'
            )
            return redirect('perfil:criar')

        # Verificar se tem algo no carrinho
        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio'
            )
            return redirect('produto:lista')

        # Verificar se o estoque é suficiente para o pedido
        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = Variacao.objects.select_related('produto').filter(
            id__in=carrinho_variacao_ids
        )
        for var in bd_variacoes:
            var_id = str(var.id)

            estoque = var.estoque
            qtd_carrinho = carrinho[var_id]['quantidade']
            preco_unit = carrinho[var_id]['preco_unitario']
            preco_unit_promo = carrinho[var_id]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[var_id]['quantidade'] = estoque
                carrinho[var_id]['preco_quantitativo'] = estoque * preco_unit
                carrinho[var_id]['preco_quantitativo_promocional'] = estoque * \
                    preco_unit_promo

                error_msg_estoque = 'Estoque insuficiente para alguns produtos '\
                    'do seu carrinho. Reduzimos a quantidade desses produtos. '\
                    'Por favor, verifique quais produtos foram afetados.'

                if error_msg_estoque:
                    messages.error(
                        self.request,
                        error_msg_estoque
                    )
                    self.request.session.save()
                    return redirect('produto:carrinho')

        print(carrinho_variacao_ids)
        print(bd_variacoes)

        qtd_total_carrinho = utils.qtd_total_carrinho(carrinho)
        vlr_total_carrinho = utils.total_carrinho(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=vlr_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promo=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']
        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/lista.html'
    paginate_by = 3
    ordering = ['-id']
    print(context_object_name)


def export(request):
    itempedido_resource = ItemPedidoResource()
    dataset = itempedido_resource.export()
    # response = HttpResponse(dataset.csv, content_type='text/csv')
    # response['Content-Disposition'] = 'attachment; filename="member.csv"'
    # response = HttpResponse(dataset.json, content_type='application/json')
    # response['Content-Disposition'] = 'attachment; filename="persons.json"'
    response = HttpResponse(
        dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="itenspedidos.xls"'
    return response


def main_view(request):
    qs = Pedido.objects.all()
    x = [x.pk for x in qs]
    y = [y.total for y in qs]
    chart = get_plot(x, y)

    return render(request, 'pedido/grafico.html', {'chart': chart})

pedido/templates/pedido/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}

{% block titulo %}{{ pedido }} | {% endblock %}

{% block conteudo %}

{% include 'partials/_pedido.html' %}

{% endblock %}

pedido/templates/pedido/grafico.html
{% extends 'base.html' %}

{% block titulo %}Gráfico de {{ user }} | {% endblock %}

{% block conteudo %}

    {% if chart %}
        <img src="data:image/png;base64, {{ chart|safe }}">

    {% endif %}

{% endblock conteudo %}

pedido/templates/pedido/lista.html
{% extends 'base.html' %}
{% load omfilters %}

{% block titulo %}Pedidos de {{ user }} | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{ user }}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for ped in pedido %}
                <tr>
                    <th scope="row">{{ ped }}</td>
                    <td>{{ ped.total|formata_preco }}</td>
                    <td>{{ ped.qtd_total }}</td>
                    <td>{{ ped.get_status_display }}</td>
                    <td>
                        <a href="{% url 'pedido:detalhe' ped.id %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col">
        <a href="{% url 'pedido:grafico' %}" class="btn btn-primary btn-block btn-lg">Ver gráfico</a>
    </div>
    <div class="col">
        <a href="{% url 'pedido:export' %}" class="btn btn-primary btn-block btn-lg">Download</a>
    </div>
</div>

{% include 'partials/_pagination.html' %}

{% endblock conteudo %}

pedido/templates/pedido/pagar.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}

{% block titulo %}Pagamento | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>

{% include 'partials/_pedido.html' %}

<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>

{% endblock %}